spring:
  application:
    name: fexcel-server
    profiles:
      active: develop

  datasource:
    url: jdbc:mysql://localhost:6670/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: czy1377449!
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 20MB

#tomcat
server:
  tomcat:
    max-threads: 60
    uri-encoding: utf-8
    accesslog:
      enabled: true
  servlet:
    context-path: /
  port: 9112

#mybatis
#mybatis:
#  type-aliases-package: cn.czy.nmtjy.model.po
#  mapper-locations:
#    - classpath:mybatis/*.xml
#  configuration-properties:
#    cacheEnabled: false
#    ####<!-- 查询时，关闭关联对象即时加载以提高性能 -->
#    lazyLoadingEnabled: true
#    ####<!-- 设置关联对象加载的形态，此处为按需加载字段(加载字段由SQL指定)，不会加载关联表的所有字段，以提高性能 -->
#    aggressiveLazyLoading: false
#    ####<!-- 对于未知的SQL查询，允许返回不同的结果集以达到通用的效果 -->
#    multipleResultSetsEnabled: true
#    ####<!-- 允许使用列标签代替列名 -->
#    useColumnLabel: true
#    ####<!-- 允许使用自定义的主键值(比如由程序生成的UUID 32位编码作为键值)，数据表的PK生成策略将被覆盖 -->
#    useGeneratedKeys: true
#    ####<!-- 给予被嵌套的resultMap以字段-属性的映射支持 -->
#    autoMappingBehavior: FULL
#    ####<!-- 对于批量更新操作缓存SQL以提高性能 -->
#    defaultExecutorType: SIMPLE
#    ####<!-- 数据库超过15秒仍未响应则超时，部分语句可单独指定超时时间 -->
#    defaultStatementTimeout: 15
#    jdbcTypeForNull: NULL
#    ####<!-- 当参数为NULL且字段列可为空的Double等类型时可直接当NULL插入 -->
#    callSettersOnNulls: true
#    ####<!-- 打印sql语句 -->
#    logPrefix: dao

logging:
  level:
    org.springframework: info
    cn.czy.nmtjy.mapper: debug
    org.springframework.security: debug
  file: ./fexcelLog/9112log.log
